<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Carbon\Carbon;

class TabelasTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('tabelas')->insert([
            ['tabela_origens_id' => 2, 'plano_id' => 1, 'acomodacao_id' => 1, 'faixa_etaria_id' => 1, 'operadora_id' => 1, 'coparticipacao' => 0, 'odonto' => 1, 'valor' => 292.47],
            ['tabela_origens_id' => 2, 'plano_id' => 1, 'acomodacao_id' => 1, 'faixa_etaria_id' => 2, 'operadora_id' => 1, 'coparticipacao' => 0, 'odonto' => 1, 'valor' => 378.15],
            ['tabela_origens_id' => 2, 'plano_id' => 1, 'acomodacao_id' => 1, 'faixa_etaria_id' => 3, 'operadora_id' => 1, 'coparticipacao' => 0, 'odonto' => 1, 'valor' => 431.16],
            ['tabela_origens_id' => 2, 'plano_id' => 1, 'acomodacao_id' => 1, 'faixa_etaria_id' => 4, 'operadora_id' => 1, 'coparticipacao' => 0, 'odonto' => 1, 'valor' => 479.93],
            ['tabela_origens_id' => 2, 'plano_id' => 1, 'acomodacao_id' => 1, 'faixa_etaria_id' => 5, 'operadora_id' => 1, 'coparticipacao' => 0, 'odonto' => 1, 'valor' => 502.69],
            ['tabela_origens_id' => 2, 'plano_id' => 1, 'acomodacao_id' => 1, 'faixa_etaria_id' => 6, 'operadora_id' => 1, 'coparticipacao' => 0, 'odonto' => 1, 'valor' => 564.82],
            ['tabela_origens_id' => 2, 'plano_id' => 1, 'acomodacao_id' => 1, 'faixa_etaria_id' => 7, 'operadora_id' => 1, 'coparticipacao' => 0, 'odonto' => 1, 'valor' => 683.64],
            ['tabela_origens_id' => 2, 'plano_id' => 1, 'acomodacao_id' => 1, 'faixa_etaria_id' => 8, 'operadora_id' => 1, 'coparticipacao' => 0, 'odonto' => 1, 'valor' => 934.03],
            ['tabela_origens_id' => 2, 'plano_id' => 1, 'acomodacao_id' => 1, 'faixa_etaria_id' => 9, 'operadora_id' => 1, 'coparticipacao' => 0, 'odonto' => 1, 'valor' => 1252.29],
            ['tabela_origens_id' => 2, 'plano_id' => 1, 'acomodacao_id' => 1, 'faixa_etaria_id' => 10, 'operadora_id' => 1, 'coparticipacao' => 0, 'odonto' => 1, 'valor' => 1620.56],
            ['tabela_origens_id' => 2, 'plano_id' => 1, 'acomodacao_id' => 2, 'faixa_etaria_id' => 1, 'operadora_id' => 1, 'coparticipacao' => 0, 'odonto' => 1, 'valor' => 230.67],
            ['tabela_origens_id' => 2, 'plano_id' => 1, 'acomodacao_id' => 2, 'faixa_etaria_id' => 2, 'operadora_id' => 1, 'coparticipacao' => 0, 'odonto' => 1, 'valor' => 296.57],
            ['tabela_origens_id' => 2, 'plano_id' => 1, 'acomodacao_id' => 2, 'faixa_etaria_id' => 3, 'operadora_id' => 1, 'coparticipacao' => 0, 'odonto' => 1, 'valor' => 337.35],
            ['tabela_origens_id' => 2, 'plano_id' => 1, 'acomodacao_id' => 2, 'faixa_etaria_id' => 4, 'operadora_id' => 1, 'coparticipacao' => 0, 'odonto' => 1, 'valor' => 374.86],
            ['tabela_origens_id' => 2, 'plano_id' => 1, 'acomodacao_id' => 2, 'faixa_etaria_id' => 5, 'operadora_id' => 1, 'coparticipacao' => 0, 'odonto' => 1, 'valor' => 392.37],
            ['tabela_origens_id' => 2, 'plano_id' => 1, 'acomodacao_id' => 2, 'faixa_etaria_id' => 6, 'operadora_id' => 1, 'coparticipacao' => 0, 'odonto' => 1, 'valor' => 440.16],
            ['tabela_origens_id' => 2, 'plano_id' => 1, 'acomodacao_id' => 2, 'faixa_etaria_id' => 7, 'operadora_id' => 1, 'coparticipacao' => 0, 'odonto' => 1, 'valor' => 531.55],
            ['tabela_origens_id' => 2, 'plano_id' => 1, 'acomodacao_id' => 2, 'faixa_etaria_id' => 8, 'operadora_id' => 1, 'coparticipacao' => 0, 'odonto' => 1, 'valor' => 724.14],
            ['tabela_origens_id' => 2, 'plano_id' => 1, 'acomodacao_id' => 2, 'faixa_etaria_id' => 9, 'operadora_id' => 1, 'coparticipacao' => 0, 'odonto' => 1, 'valor' => 968.93],
            ['tabela_origens_id' => 2, 'plano_id' => 1, 'acomodacao_id' => 2, 'faixa_etaria_id' => 10, 'operadora_id' => 1, 'coparticipacao' => 0, 'odonto' => 1, 'valor' => 1252.19],
            ['tabela_origens_id' => 2, 'plano_id' => 1, 'acomodacao_id' => 3, 'faixa_etaria_id' => 1, 'operadora_id' => 1, 'coparticipacao' => 0, 'odonto' => 1, 'valor' => 137.71],
            ['tabela_origens_id' => 2, 'plano_id' => 1, 'acomodacao_id' => 3, 'faixa_etaria_id' => 2, 'operadora_id' => 1, 'coparticipacao' => 0, 'odonto' => 1, 'valor' => 180.94],
            ['tabela_origens_id' => 2, 'plano_id' => 1, 'acomodacao_id' => 3, 'faixa_etaria_id' => 3, 'operadora_id' => 1, 'coparticipacao' => 0, 'odonto' => 1, 'valor' => 206.09],
            ['tabela_origens_id' => 2, 'plano_id' => 1, 'acomodacao_id' => 3, 'faixa_etaria_id' => 4, 'operadora_id' => 1, 'coparticipacao' => 0, 'odonto' => 1, 'valor' => 229.75],
            ['tabela_origens_id' => 2, 'plano_id' => 1, 'acomodacao_id' => 3, 'faixa_etaria_id' => 5, 'operadora_id' => 1, 'coparticipacao' => 0, 'odonto' => 1, 'valor' => 241.72],
            ['tabela_origens_id' => 2, 'plano_id' => 1, 'acomodacao_id' => 3, 'faixa_etaria_id' => 6, 'operadora_id' => 1, 'coparticipacao' => 0, 'odonto' => 1, 'valor' => 271.21],
            ['tabela_origens_id' => 2, 'plano_id' => 1, 'acomodacao_id' => 3, 'faixa_etaria_id' => 7, 'operadora_id' => 1, 'coparticipacao' => 0, 'odonto' => 1, 'valor' => 331.36],
            ['tabela_origens_id' => 2, 'plano_id' => 1, 'acomodacao_id' => 3, 'faixa_etaria_id' => 8, 'operadora_id' => 1, 'coparticipacao' => 0, 'odonto' => 1, 'valor' => 459.09],
            ['tabela_origens_id' => 2, 'plano_id' => 1, 'acomodacao_id' => 3, 'faixa_etaria_id' => 9, 'operadora_id' => 1, 'coparticipacao' => 0, 'odonto' => 1, 'valor' => 618.42],
            ['tabela_origens_id' => 2, 'plano_id' => 1, 'acomodacao_id' => 3, 'faixa_etaria_id' => 10, 'operadora_id' => 1, 'coparticipacao' => 0, 'odonto' => 1, 'valor' => 802.79],
            ['tabela_origens_id' => 2, 'plano_id' => 1, 'acomodacao_id' => 1, 'faixa_etaria_id' => 1, 'operadora_id' => 1, 'coparticipacao' => 0, 'odonto' => 0, 'valor' => 192.47],
            ['tabela_origens_id' => 2, 'plano_id' => 1, 'acomodacao_id' => 1, 'faixa_etaria_id' => 2, 'operadora_id' => 1, 'coparticipacao' => 0, 'odonto' => 0, 'valor' => 258.15],
            ['tabela_origens_id' => 2, 'plano_id' => 1, 'acomodacao_id' => 1, 'faixa_etaria_id' => 3, 'operadora_id' => 1, 'coparticipacao' => 0, 'odonto' => 0, 'valor' => 381.16],
            ['tabela_origens_id' => 2, 'plano_id' => 1, 'acomodacao_id' => 1, 'faixa_etaria_id' => 4, 'operadora_id' => 1, 'coparticipacao' => 0, 'odonto' => 0, 'valor' => 489.93],
            ['tabela_origens_id' => 2, 'plano_id' => 1, 'acomodacao_id' => 1, 'faixa_etaria_id' => 5, 'operadora_id' => 1, 'coparticipacao' => 0, 'odonto' => 0, 'valor' => 552.69],
            ['tabela_origens_id' => 2, 'plano_id' => 1, 'acomodacao_id' => 1, 'faixa_etaria_id' => 6, 'operadora_id' => 1, 'coparticipacao' => 0, 'odonto' => 0, 'valor' => 689.82],
            ['tabela_origens_id' => 2, 'plano_id' => 1, 'acomodacao_id' => 1, 'faixa_etaria_id' => 7, 'operadora_id' => 1, 'coparticipacao' => 0, 'odonto' => 0, 'valor' => 702.64],
            ['tabela_origens_id' => 2, 'plano_id' => 1, 'acomodacao_id' => 1, 'faixa_etaria_id' => 8, 'operadora_id' => 1, 'coparticipacao' => 0, 'odonto' => 0, 'valor' => 845.03],
            ['tabela_origens_id' => 2, 'plano_id' => 1, 'acomodacao_id' => 1, 'faixa_etaria_id' => 9, 'operadora_id' => 1, 'coparticipacao' => 0, 'odonto' => 0, 'valor' => 952.29],
            ['tabela_origens_id' => 2, 'plano_id' => 1, 'acomodacao_id' => 1, 'faixa_etaria_id' => 10, 'operadora_id' => 1, 'coparticipacao' => 0, 'odonto' => 0, 'valor' => 1120.56],
            ['tabela_origens_id' => 2, 'plano_id' => 1, 'acomodacao_id' => 2, 'faixa_etaria_id' => 1, 'operadora_id' => 1, 'coparticipacao' => 0, 'odonto' => 0, 'valor' => 266.67],
            ['tabela_origens_id' => 2, 'plano_id' => 1, 'acomodacao_id' => 2, 'faixa_etaria_id' => 2, 'operadora_id' => 1, 'coparticipacao' => 0, 'odonto' => 0, 'valor' => 326.57],
            ['tabela_origens_id' => 2, 'plano_id' => 1, 'acomodacao_id' => 2, 'faixa_etaria_id' => 3, 'operadora_id' => 1, 'coparticipacao' => 0, 'odonto' => 0, 'valor' => 437.35],
            ['tabela_origens_id' => 2, 'plano_id' => 1, 'acomodacao_id' => 2, 'faixa_etaria_id' => 4, 'operadora_id' => 1, 'coparticipacao' => 0, 'odonto' => 0, 'valor' => 587.86],
            ['tabela_origens_id' => 2, 'plano_id' => 1, 'acomodacao_id' => 2, 'faixa_etaria_id' => 5, 'operadora_id' => 1, 'coparticipacao' => 0, 'odonto' => 0, 'valor' => 655.37],
            ['tabela_origens_id' => 2, 'plano_id' => 1, 'acomodacao_id' => 2, 'faixa_etaria_id' => 6, 'operadora_id' => 1, 'coparticipacao' => 0, 'odonto' => 0, 'valor' => 740.16],
            ['tabela_origens_id' => 2, 'plano_id' => 1, 'acomodacao_id' => 2, 'faixa_etaria_id' => 7, 'operadora_id' => 1, 'coparticipacao' => 0, 'odonto' => 0, 'valor' => 651.55],
            ['tabela_origens_id' => 2, 'plano_id' => 1, 'acomodacao_id' => 2, 'faixa_etaria_id' => 8, 'operadora_id' => 1, 'coparticipacao' => 0, 'odonto' => 0, 'valor' => 794.14],
            ['tabela_origens_id' => 2, 'plano_id' => 1, 'acomodacao_id' => 2, 'faixa_etaria_id' => 9, 'operadora_id' => 1, 'coparticipacao' => 0, 'odonto' => 0, 'valor' => 866.93],
            ['tabela_origens_id' => 2, 'plano_id' => 1, 'acomodacao_id' => 2, 'faixa_etaria_id' => 10, 'operadora_id' => 1, 'coparticipacao' => 0, 'odonto' => 0, 'valor' => 902.19],
            ['tabela_origens_id' => 2, 'plano_id' => 1, 'acomodacao_id' => 3, 'faixa_etaria_id' => 1, 'operadora_id' => 1, 'coparticipacao' => 0, 'odonto' => 0, 'valor' => 0.00],
            ['tabela_origens_id' => 2, 'plano_id' => 1, 'acomodacao_id' => 3, 'faixa_etaria_id' => 2, 'operadora_id' => 1, 'coparticipacao' => 0, 'odonto' => 0, 'valor' => 0.00],
            ['tabela_origens_id' => 2, 'plano_id' => 1, 'acomodacao_id' => 3, 'faixa_etaria_id' => 3, 'operadora_id' => 1, 'coparticipacao' => 0, 'odonto' => 0, 'valor' => 0.00],
            ['tabela_origens_id' => 2, 'plano_id' => 1, 'acomodacao_id' => 3, 'faixa_etaria_id' => 4, 'operadora_id' => 1, 'coparticipacao' => 0, 'odonto' => 0, 'valor' => 0.00],
            ['tabela_origens_id' => 2, 'plano_id' => 1, 'acomodacao_id' => 3, 'faixa_etaria_id' => 5, 'operadora_id' => 1, 'coparticipacao' => 0, 'odonto' => 0, 'valor' => 0.00],
            ['tabela_origens_id' => 2, 'plano_id' => 1, 'acomodacao_id' => 3, 'faixa_etaria_id' => 6, 'operadora_id' => 1, 'coparticipacao' => 0, 'odonto' => 0, 'valor' => 0.00],
            ['tabela_origens_id' => 2, 'plano_id' => 1, 'acomodacao_id' => 3, 'faixa_etaria_id' => 7, 'operadora_id' => 1, 'coparticipacao' => 0, 'odonto' => 0, 'valor' => 0.00],
            ['tabela_origens_id' => 2, 'plano_id' => 1, 'acomodacao_id' => 3, 'faixa_etaria_id' => 8, 'operadora_id' => 1, 'coparticipacao' => 0, 'odonto' => 0, 'valor' => 0.00],
            ['tabela_origens_id' => 2, 'plano_id' => 1, 'acomodacao_id' => 3, 'faixa_etaria_id' => 9, 'operadora_id' => 1, 'coparticipacao' => 0, 'odonto' => 0, 'valor' => 0.00],
            ['tabela_origens_id' => 2, 'plano_id' => 1, 'acomodacao_id' => 3, 'faixa_etaria_id' => 10, 'operadora_id' => 1, 'coparticipacao' => 0, 'odonto' => 0, 'valor' => 0.00],
            ['tabela_origens_id' => 2, 'plano_id' => 1, 'acomodacao_id' => 1, 'faixa_etaria_id' => 1, 'operadora_id' => 1, 'coparticipacao' => 0, 'odonto' => 1, 'valor' => 192.47],
            ['tabela_origens_id' => 2, 'plano_id' => 1, 'acomodacao_id' => 1, 'faixa_etaria_id' => 2, 'operadora_id' => 1, 'coparticipacao' => 0, 'odonto' => 1, 'valor' => 258.15],
            ['tabela_origens_id' => 2, 'plano_id' => 1, 'acomodacao_id' => 1, 'faixa_etaria_id' => 3, 'operadora_id' => 1, 'coparticipacao' => 0, 'odonto' => 1, 'valor' => 381.16],
            ['tabela_origens_id' => 2, 'plano_id' => 1, 'acomodacao_id' => 1, 'faixa_etaria_id' => 4, 'operadora_id' => 1, 'coparticipacao' => 0, 'odonto' => 1, 'valor' => 489.93],
            ['tabela_origens_id' => 2, 'plano_id' => 1, 'acomodacao_id' => 1, 'faixa_etaria_id' => 5, 'operadora_id' => 1, 'coparticipacao' => 0, 'odonto' => 1, 'valor' => 552.69],
            ['tabela_origens_id' => 2, 'plano_id' => 1, 'acomodacao_id' => 1, 'faixa_etaria_id' => 6, 'operadora_id' => 1, 'coparticipacao' => 0, 'odonto' => 1, 'valor' => 689.82],
            ['tabela_origens_id' => 2, 'plano_id' => 1, 'acomodacao_id' => 1, 'faixa_etaria_id' => 7, 'operadora_id' => 1, 'coparticipacao' => 0, 'odonto' => 1, 'valor' => 702.64],
            ['tabela_origens_id' => 2, 'plano_id' => 1, 'acomodacao_id' => 1, 'faixa_etaria_id' => 8, 'operadora_id' => 1, 'coparticipacao' => 0, 'odonto' => 1, 'valor' => 845.03],
            ['tabela_origens_id' => 2, 'plano_id' => 1, 'acomodacao_id' => 1, 'faixa_etaria_id' => 9, 'operadora_id' => 1, 'coparticipacao' => 0, 'odonto' => 1, 'valor' => 952.29],
            ['tabela_origens_id' => 2, 'plano_id' => 1, 'acomodacao_id' => 1, 'faixa_etaria_id' => 10, 'operadora_id' => 1, 'coparticipacao' => 0, 'odonto' => 1, 'valor' => 1120.56],
            ['tabela_origens_id' => 2, 'plano_id' => 1, 'acomodacao_id' => 2, 'faixa_etaria_id' => 1, 'operadora_id' => 1, 'coparticipacao' => 0, 'odonto' => 1, 'valor' => 266.67],
            ['tabela_origens_id' => 2, 'plano_id' => 1, 'acomodacao_id' => 2, 'faixa_etaria_id' => 2, 'operadora_id' => 1, 'coparticipacao' => 0, 'odonto' => 1, 'valor' => 326.57],
            ['tabela_origens_id' => 2, 'plano_id' => 1, 'acomodacao_id' => 2, 'faixa_etaria_id' => 3, 'operadora_id' => 1, 'coparticipacao' => 0, 'odonto' => 1, 'valor' => 437.35],
            ['tabela_origens_id' => 2, 'plano_id' => 1, 'acomodacao_id' => 2, 'faixa_etaria_id' => 4, 'operadora_id' => 1, 'coparticipacao' => 0, 'odonto' => 1, 'valor' => 587.86],
            ['tabela_origens_id' => 2, 'plano_id' => 1, 'acomodacao_id' => 2, 'faixa_etaria_id' => 5, 'operadora_id' => 1, 'coparticipacao' => 0, 'odonto' => 1, 'valor' => 655.37],
            ['tabela_origens_id' => 2, 'plano_id' => 1, 'acomodacao_id' => 2, 'faixa_etaria_id' => 6, 'operadora_id' => 1, 'coparticipacao' => 0, 'odonto' => 1, 'valor' => 740.16],
            ['tabela_origens_id' => 2, 'plano_id' => 1, 'acomodacao_id' => 2, 'faixa_etaria_id' => 7, 'operadora_id' => 1, 'coparticipacao' => 0, 'odonto' => 1, 'valor' => 651.55],
            ['tabela_origens_id' => 2, 'plano_id' => 1, 'acomodacao_id' => 2, 'faixa_etaria_id' => 8, 'operadora_id' => 1, 'coparticipacao' => 0, 'odonto' => 1, 'valor' => 794.14],
            ['tabela_origens_id' => 2, 'plano_id' => 1, 'acomodacao_id' => 2, 'faixa_etaria_id' => 9, 'operadora_id' => 1, 'coparticipacao' => 0, 'odonto' => 1, 'valor' => 866.93],
            ['tabela_origens_id' => 2, 'plano_id' => 1, 'acomodacao_id' => 2, 'faixa_etaria_id' => 10, 'operadora_id' => 1, 'coparticipacao' => 0, 'odonto' => 1, 'valor' => 902.19],
            ['tabela_origens_id' => 2, 'plano_id' => 1, 'acomodacao_id' => 3, 'faixa_etaria_id' => 1, 'operadora_id' => 1, 'coparticipacao' => 0, 'odonto' => 1, 'valor' => 0.00],
            ['tabela_origens_id' => 2, 'plano_id' => 1, 'acomodacao_id' => 3, 'faixa_etaria_id' => 2, 'operadora_id' => 1, 'coparticipacao' => 0, 'odonto' => 1, 'valor' => 0.00],
            ['tabela_origens_id' => 2, 'plano_id' => 1, 'acomodacao_id' => 3, 'faixa_etaria_id' => 3, 'operadora_id' => 1, 'coparticipacao' => 0, 'odonto' => 1, 'valor' => 0.00],
            ['tabela_origens_id' => 2, 'plano_id' => 1, 'acomodacao_id' => 3, 'faixa_etaria_id' => 4, 'operadora_id' => 1, 'coparticipacao' => 0, 'odonto' => 1, 'valor' => 0.00],
            ['tabela_origens_id' => 2, 'plano_id' => 1, 'acomodacao_id' => 3, 'faixa_etaria_id' => 5, 'operadora_id' => 1, 'coparticipacao' => 0, 'odonto' => 1, 'valor' => 0.00],
            ['tabela_origens_id' => 2, 'plano_id' => 1, 'acomodacao_id' => 3, 'faixa_etaria_id' => 6, 'operadora_id' => 1, 'coparticipacao' => 0, 'odonto' => 1, 'valor' => 0.00],
            ['tabela_origens_id' => 2, 'plano_id' => 1, 'acomodacao_id' => 3, 'faixa_etaria_id' => 7, 'operadora_id' => 1, 'coparticipacao' => 0, 'odonto' => 1, 'valor' => 0.00],
            ['tabela_origens_id' => 2, 'plano_id' => 1, 'acomodacao_id' => 3, 'faixa_etaria_id' => 8, 'operadora_id' => 1, 'coparticipacao' => 0, 'odonto' => 1, 'valor' => 0.00],
            ['tabela_origens_id' => 2, 'plano_id' => 1, 'acomodacao_id' => 3, 'faixa_etaria_id' => 9, 'operadora_id' => 1, 'coparticipacao' => 0, 'odonto' => 1, 'valor' => 0.00],
            ['tabela_origens_id' => 2, 'plano_id' => 1, 'acomodacao_id' => 3, 'faixa_etaria_id' => 10, 'operadora_id' => 1, 'coparticipacao' => 0, 'odonto' => 1, 'valor' => 0.00],
            ['tabela_origens_id' => 2, 'plano_id' => 1, 'acomodacao_id' => 1, 'faixa_etaria_id' => 1, 'operadora_id' => 1, 'coparticipacao' => 0, 'odonto' => 0, 'valor' => 192.47],
            ['tabela_origens_id' => 2, 'plano_id' => 1, 'acomodacao_id' => 1, 'faixa_etaria_id' => 2, 'operadora_id' => 1, 'coparticipacao' => 0, 'odonto' => 0, 'valor' => 258.15],
            ['tabela_origens_id' => 2, 'plano_id' => 1, 'acomodacao_id' => 1, 'faixa_etaria_id' => 3, 'operadora_id' => 1, 'coparticipacao' => 0, 'odonto' => 0, 'valor' => 381.16],
            ['tabela_origens_id' => 2, 'plano_id' => 1, 'acomodacao_id' => 1, 'faixa_etaria_id' => 4, 'operadora_id' => 1, 'coparticipacao' => 0, 'odonto' => 0, 'valor' => 489.93],
            ['tabela_origens_id' => 2, 'plano_id' => 1, 'acomodacao_id' => 1, 'faixa_etaria_id' => 5, 'operadora_id' => 1, 'coparticipacao' => 0, 'odonto' => 0, 'valor' => 552.69],
            ['tabela_origens_id' => 2, 'plano_id' => 1, 'acomodacao_id' => 1, 'faixa_etaria_id' => 6, 'operadora_id' => 1, 'coparticipacao' => 0, 'odonto' => 0, 'valor' => 689.82],
            ['tabela_origens_id' => 2, 'plano_id' => 1, 'acomodacao_id' => 1, 'faixa_etaria_id' => 7, 'operadora_id' => 1, 'coparticipacao' => 0, 'odonto' => 0, 'valor' => 702.64],
            ['tabela_origens_id' => 2, 'plano_id' => 1, 'acomodacao_id' => 1, 'faixa_etaria_id' => 8, 'operadora_id' => 1, 'coparticipacao' => 0, 'odonto' => 0, 'valor' => 845.03],
            ['tabela_origens_id' => 2, 'plano_id' => 1, 'acomodacao_id' => 1, 'faixa_etaria_id' => 9, 'operadora_id' => 1, 'coparticipacao' => 0, 'odonto' => 0, 'valor' => 952.29],
            ['tabela_origens_id' => 2, 'plano_id' => 1, 'acomodacao_id' => 1, 'faixa_etaria_id' => 10, 'operadora_id' => 1, 'coparticipacao' => 0, 'odonto' => 0, 'valor' => 1120.56],
            ['tabela_origens_id' => 2, 'plano_id' => 1, 'acomodacao_id' => 2, 'faixa_etaria_id' => 1, 'operadora_id' => 1, 'coparticipacao' => 0, 'odonto' => 0, 'valor' => 266.67],
            ['tabela_origens_id' => 2, 'plano_id' => 1, 'acomodacao_id' => 2, 'faixa_etaria_id' => 2, 'operadora_id' => 1, 'coparticipacao' => 0, 'odonto' => 0, 'valor' => 326.57],
            ['tabela_origens_id' => 2, 'plano_id' => 1, 'acomodacao_id' => 2, 'faixa_etaria_id' => 3, 'operadora_id' => 1, 'coparticipacao' => 0, 'odonto' => 0, 'valor' => 437.35],
            ['tabela_origens_id' => 2, 'plano_id' => 1, 'acomodacao_id' => 2, 'faixa_etaria_id' => 4, 'operadora_id' => 1, 'coparticipacao' => 0, 'odonto' => 0, 'valor' => 587.86],
            ['tabela_origens_id' => 2, 'plano_id' => 1, 'acomodacao_id' => 2, 'faixa_etaria_id' => 5, 'operadora_id' => 1, 'coparticipacao' => 0, 'odonto' => 0, 'valor' => 655.37],
            ['tabela_origens_id' => 2, 'plano_id' => 1, 'acomodacao_id' => 2, 'faixa_etaria_id' => 6, 'operadora_id' => 1, 'coparticipacao' => 0, 'odonto' => 0, 'valor' => 740.16],
            ['tabela_origens_id' => 2, 'plano_id' => 1, 'acomodacao_id' => 2, 'faixa_etaria_id' => 7, 'operadora_id' => 1, 'coparticipacao' => 0, 'odonto' => 0, 'valor' => 651.55],
            ['tabela_origens_id' => 2, 'plano_id' => 1, 'acomodacao_id' => 2, 'faixa_etaria_id' => 8, 'operadora_id' => 1, 'coparticipacao' => 0, 'odonto' => 0, 'valor' => 794.14],
            ['tabela_origens_id' => 2, 'plano_id' => 1, 'acomodacao_id' => 2, 'faixa_etaria_id' => 9, 'operadora_id' => 1, 'coparticipacao' => 0, 'odonto' => 0, 'valor' => 866.93],
            ['tabela_origens_id' => 2, 'plano_id' => 1, 'acomodacao_id' => 2, 'faixa_etaria_id' => 10, 'operadora_id' => 1, 'coparticipacao' => 0, 'odonto' => 0, 'valor' => 902.19],
            ['tabela_origens_id' => 2, 'plano_id' => 1, 'acomodacao_id' => 3, 'faixa_etaria_id' => 1, 'operadora_id' => 1, 'coparticipacao' => 0, 'odonto' => 0, 'valor' => 0.00],
            ['tabela_origens_id' => 2, 'plano_id' => 1, 'acomodacao_id' => 3, 'faixa_etaria_id' => 2, 'operadora_id' => 1, 'coparticipacao' => 0, 'odonto' => 0, 'valor' => 0.00],
            ['tabela_origens_id' => 2, 'plano_id' => 1, 'acomodacao_id' => 3, 'faixa_etaria_id' => 3, 'operadora_id' => 1, 'coparticipacao' => 0, 'odonto' => 0, 'valor' => 0.00],
            ['tabela_origens_id' => 2, 'plano_id' => 1, 'acomodacao_id' => 3, 'faixa_etaria_id' => 4, 'operadora_id' => 1, 'coparticipacao' => 0, 'odonto' => 0, 'valor' => 0.00],
            ['tabela_origens_id' => 2, 'plano_id' => 1, 'acomodacao_id' => 3, 'faixa_etaria_id' => 5, 'operadora_id' => 1, 'coparticipacao' => 0, 'odonto' => 0, 'valor' => 0.00],
            ['tabela_origens_id' => 2, 'plano_id' => 1, 'acomodacao_id' => 3, 'faixa_etaria_id' => 6, 'operadora_id' => 1, 'coparticipacao' => 0, 'odonto' => 0, 'valor' => 0.00],
            ['tabela_origens_id' => 2, 'plano_id' => 1, 'acomodacao_id' => 3, 'faixa_etaria_id' => 7, 'operadora_id' => 1, 'coparticipacao' => 0, 'odonto' => 0, 'valor' => 0.00],
            ['tabela_origens_id' => 2, 'plano_id' => 1, 'acomodacao_id' => 3, 'faixa_etaria_id' => 8, 'operadora_id' => 1, 'coparticipacao' => 0, 'odonto' => 0, 'valor' => 0.00],
            ['tabela_origens_id' => 2, 'plano_id' => 1, 'acomodacao_id' => 3, 'faixa_etaria_id' => 9, 'operadora_id' => 1, 'coparticipacao' => 0, 'odonto' => 0, 'valor' => 0.00],
            ['tabela_origens_id' => 2, 'plano_id' => 1, 'acomodacao_id' => 3, 'faixa_etaria_id' => 10, 'operadora_id' => 1, 'coparticipacao' => 0, 'odonto' => 0, 'valor' => 0.00],
            ['tabela_origens_id' => 2, 'plano_id' => 1, 'acomodacao_id' => 1, 'faixa_etaria_id' => 1, 'operadora_id' => 1, 'coparticipacao' => 1, 'odonto' => 1, 'valor' => 192.47],
            ['tabela_origens_id' => 2, 'plano_id' => 1, 'acomodacao_id' => 1, 'faixa_etaria_id' => 2, 'operadora_id' => 1, 'coparticipacao' => 1, 'odonto' => 1, 'valor' => 258.15],
            ['tabela_origens_id' => 2, 'plano_id' => 1, 'acomodacao_id' => 1, 'faixa_etaria_id' => 3, 'operadora_id' => 1, 'coparticipacao' => 1, 'odonto' => 1, 'valor' => 381.16],
            ['tabela_origens_id' => 2, 'plano_id' => 1, 'acomodacao_id' => 1, 'faixa_etaria_id' => 4, 'operadora_id' => 1, 'coparticipacao' => 1, 'odonto' => 1, 'valor' => 489.93],
            ['tabela_origens_id' => 2, 'plano_id' => 1, 'acomodacao_id' => 1, 'faixa_etaria_id' => 5, 'operadora_id' => 1, 'coparticipacao' => 1, 'odonto' => 1, 'valor' => 552.69],
            ['tabela_origens_id' => 2, 'plano_id' => 1, 'acomodacao_id' => 1, 'faixa_etaria_id' => 6, 'operadora_id' => 1, 'coparticipacao' => 1, 'odonto' => 1, 'valor' => 689.82],
            ['tabela_origens_id' => 2, 'plano_id' => 1, 'acomodacao_id' => 1, 'faixa_etaria_id' => 7, 'operadora_id' => 1, 'coparticipacao' => 1, 'odonto' => 1, 'valor' => 702.64],
            ['tabela_origens_id' => 2, 'plano_id' => 1, 'acomodacao_id' => 1, 'faixa_etaria_id' => 8, 'operadora_id' => 1, 'coparticipacao' => 1, 'odonto' => 1, 'valor' => 845.03],
            ['tabela_origens_id' => 2, 'plano_id' => 1, 'acomodacao_id' => 1, 'faixa_etaria_id' => 9, 'operadora_id' => 1, 'coparticipacao' => 1, 'odonto' => 1, 'valor' => 952.29],
            ['tabela_origens_id' => 2, 'plano_id' => 1, 'acomodacao_id' => 1, 'faixa_etaria_id' => 10, 'operadora_id' => 1, 'coparticipacao' => 1, 'odonto' => 1, 'valor' => 1120.56],
            ['tabela_origens_id' => 2, 'plano_id' => 1, 'acomodacao_id' => 2, 'faixa_etaria_id' => 1, 'operadora_id' => 1, 'coparticipacao' => 1, 'odonto' => 1, 'valor' => 266.67],
            ['tabela_origens_id' => 2, 'plano_id' => 1, 'acomodacao_id' => 2, 'faixa_etaria_id' => 2, 'operadora_id' => 1, 'coparticipacao' => 1, 'odonto' => 1, 'valor' => 326.57],
            ['tabela_origens_id' => 2, 'plano_id' => 1, 'acomodacao_id' => 2, 'faixa_etaria_id' => 3, 'operadora_id' => 1, 'coparticipacao' => 1, 'odonto' => 1, 'valor' => 437.35],
            ['tabela_origens_id' => 2, 'plano_id' => 1, 'acomodacao_id' => 2, 'faixa_etaria_id' => 4, 'operadora_id' => 1, 'coparticipacao' => 1, 'odonto' => 1, 'valor' => 587.86],
            ['tabela_origens_id' => 2, 'plano_id' => 1, 'acomodacao_id' => 2, 'faixa_etaria_id' => 5, 'operadora_id' => 1, 'coparticipacao' => 1, 'odonto' => 1, 'valor' => 655.37],
            ['tabela_origens_id' => 2, 'plano_id' => 1, 'acomodacao_id' => 2, 'faixa_etaria_id' => 6, 'operadora_id' => 1, 'coparticipacao' => 1, 'odonto' => 1, 'valor' => 740.16],
            ['tabela_origens_id' => 2, 'plano_id' => 1, 'acomodacao_id' => 2, 'faixa_etaria_id' => 7, 'operadora_id' => 1, 'coparticipacao' => 1, 'odonto' => 1, 'valor' => 651.55],
            ['tabela_origens_id' => 2, 'plano_id' => 1, 'acomodacao_id' => 2, 'faixa_etaria_id' => 8, 'operadora_id' => 1, 'coparticipacao' => 1, 'odonto' => 1, 'valor' => 794.14],
            ['tabela_origens_id' => 2, 'plano_id' => 1, 'acomodacao_id' => 2, 'faixa_etaria_id' => 9, 'operadora_id' => 1, 'coparticipacao' => 1, 'odonto' => 1, 'valor' => 866.93],
            ['tabela_origens_id' => 2, 'plano_id' => 1, 'acomodacao_id' => 2, 'faixa_etaria_id' => 10, 'operadora_id' => 1, 'coparticipacao' => 1, 'odonto' => 1, 'valor' => 902.19],
            ['tabela_origens_id' => 2, 'plano_id' => 1, 'acomodacao_id' => 3, 'faixa_etaria_id' => 1, 'operadora_id' => 1, 'coparticipacao' => 1, 'odonto' => 1, 'valor' => 0.00],
            ['tabela_origens_id' => 2, 'plano_id' => 1, 'acomodacao_id' => 3, 'faixa_etaria_id' => 2, 'operadora_id' => 1, 'coparticipacao' => 1, 'odonto' => 1, 'valor' => 0.00],
            ['tabela_origens_id' => 2, 'plano_id' => 1, 'acomodacao_id' => 3, 'faixa_etaria_id' => 3, 'operadora_id' => 1, 'coparticipacao' => 1, 'odonto' => 1, 'valor' => 0.00],
            ['tabela_origens_id' => 2, 'plano_id' => 1, 'acomodacao_id' => 3, 'faixa_etaria_id' => 4, 'operadora_id' => 1, 'coparticipacao' => 1, 'odonto' => 1, 'valor' => 0.00],
            ['tabela_origens_id' => 2, 'plano_id' => 1, 'acomodacao_id' => 3, 'faixa_etaria_id' => 5, 'operadora_id' => 1, 'coparticipacao' => 1, 'odonto' => 1, 'valor' => 0.00],
            ['tabela_origens_id' => 2, 'plano_id' => 1, 'acomodacao_id' => 3, 'faixa_etaria_id' => 6, 'operadora_id' => 1, 'coparticipacao' => 1, 'odonto' => 1, 'valor' => 0.00],
            ['tabela_origens_id' => 2, 'plano_id' => 1, 'acomodacao_id' => 3, 'faixa_etaria_id' => 7, 'operadora_id' => 1, 'coparticipacao' => 1, 'odonto' => 1, 'valor' => 0.00],
            ['tabela_origens_id' => 2, 'plano_id' => 1, 'acomodacao_id' => 3, 'faixa_etaria_id' => 8, 'operadora_id' => 1, 'coparticipacao' => 1, 'odonto' => 1, 'valor' => 0.00],
            ['tabela_origens_id' => 2, 'plano_id' => 1, 'acomodacao_id' => 3, 'faixa_etaria_id' => 9, 'operadora_id' => 1, 'coparticipacao' => 1, 'odonto' => 1, 'valor' => 0.00],
            ['tabela_origens_id' => 2, 'plano_id' => 1, 'acomodacao_id' => 3, 'faixa_etaria_id' => 10, 'operadora_id' => 1, 'coparticipacao' => 1, 'odonto' => 1, 'valor' => 0.00],
            ['tabela_origens_id' => 2, 'plano_id' => 1, 'acomodacao_id' => 1, 'faixa_etaria_id' => 1, 'operadora_id' => 1, 'coparticipacao' => 1, 'odonto' => 0, 'valor' => 192.47],
            ['tabela_origens_id' => 2, 'plano_id' => 1, 'acomodacao_id' => 1, 'faixa_etaria_id' => 2, 'operadora_id' => 1, 'coparticipacao' => 1, 'odonto' => 0, 'valor' => 258.15],
            ['tabela_origens_id' => 2, 'plano_id' => 1, 'acomodacao_id' => 1, 'faixa_etaria_id' => 3, 'operadora_id' => 1, 'coparticipacao' => 1, 'odonto' => 0, 'valor' => 381.16],
            ['tabela_origens_id' => 2, 'plano_id' => 1, 'acomodacao_id' => 1, 'faixa_etaria_id' => 4, 'operadora_id' => 1, 'coparticipacao' => 1, 'odonto' => 0, 'valor' => 489.93],
            ['tabela_origens_id' => 2, 'plano_id' => 1, 'acomodacao_id' => 1, 'faixa_etaria_id' => 5, 'operadora_id' => 1, 'coparticipacao' => 1, 'odonto' => 0, 'valor' => 552.69],
            ['tabela_origens_id' => 2, 'plano_id' => 1, 'acomodacao_id' => 1, 'faixa_etaria_id' => 6, 'operadora_id' => 1, 'coparticipacao' => 1, 'odonto' => 0, 'valor' => 689.82],
            ['tabela_origens_id' => 2, 'plano_id' => 1, 'acomodacao_id' => 1, 'faixa_etaria_id' => 7, 'operadora_id' => 1, 'coparticipacao' => 1, 'odonto' => 0, 'valor' => 702.64],
            ['tabela_origens_id' => 2, 'plano_id' => 1, 'acomodacao_id' => 1, 'faixa_etaria_id' => 8, 'operadora_id' => 1, 'coparticipacao' => 1, 'odonto' => 0, 'valor' => 845.03],
            ['tabela_origens_id' => 2, 'plano_id' => 1, 'acomodacao_id' => 1, 'faixa_etaria_id' => 9, 'operadora_id' => 1, 'coparticipacao' => 1, 'odonto' => 0, 'valor' => 952.29],
            ['tabela_origens_id' => 2, 'plano_id' => 1, 'acomodacao_id' => 1, 'faixa_etaria_id' => 10, 'operadora_id' => 1, 'coparticipacao' => 1, 'odonto' => 0, 'valor' => 1120.56],
            ['tabela_origens_id' => 2, 'plano_id' => 1, 'acomodacao_id' => 2, 'faixa_etaria_id' => 1, 'operadora_id' => 1, 'coparticipacao' => 1, 'odonto' => 0, 'valor' => 266.67],
            ['tabela_origens_id' => 2, 'plano_id' => 1, 'acomodacao_id' => 2, 'faixa_etaria_id' => 2, 'operadora_id' => 1, 'coparticipacao' => 1, 'odonto' => 0, 'valor' => 326.57],
            ['tabela_origens_id' => 2, 'plano_id' => 1, 'acomodacao_id' => 2, 'faixa_etaria_id' => 3, 'operadora_id' => 1, 'coparticipacao' => 1, 'odonto' => 0, 'valor' => 437.35],
            ['tabela_origens_id' => 2, 'plano_id' => 1, 'acomodacao_id' => 2, 'faixa_etaria_id' => 4, 'operadora_id' => 1, 'coparticipacao' => 1, 'odonto' => 0, 'valor' => 587.86],
            ['tabela_origens_id' => 2, 'plano_id' => 1, 'acomodacao_id' => 2, 'faixa_etaria_id' => 5, 'operadora_id' => 1, 'coparticipacao' => 1, 'odonto' => 0, 'valor' => 655.37],
            ['tabela_origens_id' => 2, 'plano_id' => 1, 'acomodacao_id' => 2, 'faixa_etaria_id' => 6, 'operadora_id' => 1, 'coparticipacao' => 1, 'odonto' => 0, 'valor' => 740.16],
            ['tabela_origens_id' => 2, 'plano_id' => 1, 'acomodacao_id' => 2, 'faixa_etaria_id' => 7, 'operadora_id' => 1, 'coparticipacao' => 1, 'odonto' => 0, 'valor' => 651.55],
            ['tabela_origens_id' => 2, 'plano_id' => 1, 'acomodacao_id' => 2, 'faixa_etaria_id' => 8, 'operadora_id' => 1, 'coparticipacao' => 1, 'odonto' => 0, 'valor' => 794.14],
            ['tabela_origens_id' => 2, 'plano_id' => 1, 'acomodacao_id' => 2, 'faixa_etaria_id' => 9, 'operadora_id' => 1, 'coparticipacao' => 1, 'odonto' => 0, 'valor' => 866.93],
            ['tabela_origens_id' => 2, 'plano_id' => 1, 'acomodacao_id' => 2, 'faixa_etaria_id' => 10, 'operadora_id' => 1, 'coparticipacao' => 1, 'odonto' => 0, 'valor' => 902.19],
            ['tabela_origens_id' => 2, 'plano_id' => 1, 'acomodacao_id' => 3, 'faixa_etaria_id' => 1, 'operadora_id' => 1, 'coparticipacao' => 1, 'odonto' => 0, 'valor' => 0.00],
            ['tabela_origens_id' => 2, 'plano_id' => 1, 'acomodacao_id' => 3, 'faixa_etaria_id' => 2, 'operadora_id' => 1, 'coparticipacao' => 1, 'odonto' => 0, 'valor' => 0.00],
            ['tabela_origens_id' => 2, 'plano_id' => 1, 'acomodacao_id' => 3, 'faixa_etaria_id' => 3, 'operadora_id' => 1, 'coparticipacao' => 1, 'odonto' => 0, 'valor' => 0.00],
            ['tabela_origens_id' => 2, 'plano_id' => 1, 'acomodacao_id' => 3, 'faixa_etaria_id' => 4, 'operadora_id' => 1, 'coparticipacao' => 1, 'odonto' => 0, 'valor' => 0.00],
            ['tabela_origens_id' => 2, 'plano_id' => 1, 'acomodacao_id' => 3, 'faixa_etaria_id' => 5, 'operadora_id' => 1, 'coparticipacao' => 1, 'odonto' => 0, 'valor' => 0.00],
            ['tabela_origens_id' => 2, 'plano_id' => 1, 'acomodacao_id' => 3, 'faixa_etaria_id' => 6, 'operadora_id' => 1, 'coparticipacao' => 1, 'odonto' => 0, 'valor' => 0.00],
            ['tabela_origens_id' => 2, 'plano_id' => 1, 'acomodacao_id' => 3, 'faixa_etaria_id' => 7, 'operadora_id' => 1, 'coparticipacao' => 1, 'odonto' => 0, 'valor' => 0.00],
            ['tabela_origens_id' => 2, 'plano_id' => 1, 'acomodacao_id' => 3, 'faixa_etaria_id' => 8, 'operadora_id' => 1, 'coparticipacao' => 1, 'odonto' => 0, 'valor' => 0.00],
            ['tabela_origens_id' => 2, 'plano_id' => 1, 'acomodacao_id' => 3, 'faixa_etaria_id' => 9, 'operadora_id' => 1, 'coparticipacao' => 1, 'odonto' => 0, 'valor' => 0.00],
            ['tabela_origens_id' => 2, 'plano_id' => 1, 'acomodacao_id' => 3, 'faixa_etaria_id' => 10, 'operadora_id' => 1, 'coparticipacao' => 1, 'odonto' => 0, 'valor' => 0.00]





        ]);
    }
}
